export type Env = {
  DISCORD_BOT_ID: string;
  DISCORD_PUBLIC_KEY: string;
  CONSOLE_LOG: string;
  MONGO_DB: string;
  DOMAIN: string;
  DOWNLOAD_PASS: string;
  HTTPS: string;
  NPM_CONFIG_PRODUCTION: string;
  PREFIX: string;
  DISCORD_SECRET: string;
  SELFBOT_TOKEN: string;
  SENTRY: string;
  DISCORD_TOKEN: string;
  TOPTOKEN: string;
  VOIDTOKEN: string;
  WEBHOOK: string;
  WEBLOG_API: string;
  WEBLOG_CONSOLE: string;
  DISCORD_GUILD_ID: string;
  MODE: string;
  LOGS_CHANNEL_ID: string;
};