client.on("message", message => {
 /*
 if (message.content.startsWith("https://discord.com/channels/")) {
  message.content = message.content.replace("https://discord.com/channels/", "");
  const ar = message.content.split("/");
  //[guid,chid,msgid]
  try {
   const guid = ar[0];
   const chid = ar[1];
   const msgid = ar[2];
   client.guilds.cache.get(guid).channels.cache.get(chid).messages.fetch(msgid).then(msg => {
    const hmm = new Discord.MessageEmbed()
    .setTitle("Message content of Link posted above")
    .setURL("https://discord.com/channels/"+message.content)
    .setColor("RANDOM")
    .setThumbnail(msg.author.displayAvatarURL())
    .setDescription(msg.content)
    .setFooter(`By ${msg.author.tag} | in ${msg.channel.name} of ${msg.guild.name} server | Auto-Generated by RDL bot.`);
    message.channel.send(hmm);
   });
  }
  catch (e) {
   message.reply(e);
  }
 }*/
 if (!message.content.startsWith(prefix) || message.author.bot) return;
 let args = message.content.slice(prefix.length).trim().split(/ +/);
 let command = args.shift().toLowerCase();
 if (command == "" || !command) message.reply("Nani? Say it Clearly!");
 else if (command == "reload") {
  if (message.content.includes("--force")) {
   if (!client.owners.includes(message.author.id)) {
    message.reply("Baka! You're not even allowed to do so!");
   }
   else {
    reload();
    message.reply("Kyōsei!? When i will be a owner, i will force you then!\nTokorode, Events and Commands are being reloaded!");
   }
  }
  else {
   let cdm = searchCommand("help");
   if (!cdm) {
    message.reply("Rirōdo? Ok, Reloading Commands and Events!");
    reload();
   }
   else {
    message.reply("Chottomatte! I think the commands are already there. Use `--force` to force reload!");
   }
  }
 }
 else {
  try{
  let cmd = searchCommand(command);
   if (!cmd) return message.reply("Baka! That Komando Sonzai suru!");
   else eval(cmd.code);
 }
  catch(e){
   message.reply(`Nani?!\nI got an Error!\n\`\`\`\n${e}\n\`\`\``);
  }
 }
});