client.on("messageCreate", (message) => {
  if (message.content.startsWith("https://discord.com/channels/")) {
    message.content = message.content.replace(
      "https://discord.com/channels/",
      ""
    );
    const ar = message.content.split("/");
    //[guid,chid,msgid]
    try {
      const guid = ar[0];
      const chid = ar[1];
      const msgid = ar[2];
      client.guilds.cache
        .get(guid)
        .channels.cache.get(chid)
        .messages.fetch(msgid)
        .then((msg) => {
          const hmm = new Discord.MessageEmbed()
            .setTitle("Message content of Link posted above")
            .setURL("https://discord.com/channels/" + message.content)
            .setColor("RANDOM")
            .setThumbnail(msg.author.displayAvatarURL())
            .setDescription(msg.content)
            .setFooter(
              `By ${msg.author.tag} | in ${msg.channel.name} of ${msg.guild.name} server | Auto-Generated by RDL bot.`
            );
          message.channel.send({ embeds: [hmm] });
        });
    } catch (e) {
      message.reply(e);
    }
  }
  if (!message.content.startsWith(prefix) || message.author.bot) return;
  let args = message.content.slice(prefix.length).trim().split(/ +/);
  let command = args.shift().toLowerCase();
  if (command == "" || !command) message.reply("What do you want?");
  else if (command == "reload") {
    if (message.content.includes("--force")) {
      if (!client.owners.includes(message.author.id)) {
        message.reply("You're not a owner, so you can't force me.");
      } else {
        reload();
        message.reply("**Force** Reloading Commands and Events!");
      }
    } else {
      let cdm = searchCommand("help");
      if (!cdm) {
        message.reply("Reloading Commands and Events!");
        reload();
      } else {
        message.reply(
          "I think the commands are already there. Use `--force` to force reload!"
        );
      }
    }
  } else {
    try {
      let cmd = searchCommand(command);
      if (!cmd) return message.reply("That command Doesn't exist!");
      else {
        try {
          (`(async()=>{${cmd.code}})()`);
        } catch (e) {
          message.reply(
            "An Error Occured!\n```\n" + e.stack.slice(0, 1800) + "...\n```"
          );
          console.warn(
            "[BOT] Error!\n```\n" +
              e.stack.slice(0, 1880) +
              "...\n```\nUser:\n```\n" +
              JSON.stringify(message.author) +
              "\n```"
          );
        }
      }
    } catch (e) {
      message.reply(
        `An Error Occured!\n\`\`\`\n${e.stack.slice(0, 1980)}\n\`\`\``
      );
    }
  }
});
